Repository FRONT-END-BOOTCAMP-PLUS-3/moongchija, pull requests merged in 2025-02, with the labels that each got.

#79 [feat] 투표기능 관련 repository 추가
  domain/entities/PlaceVote.ts
  domain/entities/PlaceVoteUser.ts
  domain/entities/TimeVote.ts
  domain/entities/TimeVoteUser.ts
  domain/repositories/PlaceVoteRepository.ts
  domain/repositories/PlaceVoteUserRepository.ts
  domain/repositories/TimeVoteRepository.ts
  domain/repositories/TimeVoteUserRepository.ts
  infrastructure/repositories/SbPlaceVoteRepository.ts
  infrastructure/repositories/SbPlaceVoteUserRepository.ts
  infrastructure/repositories/SbTimeVoteRepository.ts
  infrastructure/repositories/SbTimeVoteUserRepository.ts
Labels: ✨ feat

#81 [feat] 장소투표 리스트 get구현, 투표제출기능 구현 중
  app/api/user/appointments/[id]/place-vote/route.ts
  app/api/user/appointments/[id]/vote/route.ts
  app/user/appointments/[id]/vote-place/page.tsx
  application/usecases/appointment/DfGetPlaceVotesUsecase.ts
  application/usecases/appointment/DfSubmitVoteUsecase.ts
  application/usecases/appointment/dto/PlaceVoteDto.ts
  application/usecases/appointment/dto/VoteDto.ts
  domain/repositories/TimeVoteRepository.ts
  infrastructure/repositories/SbTimeVoteRepository.ts
  package-lock.json
  package.json
  utils/supabase/client.ts
  utils/supabase/cookieHelper.ts
Labels: ✨ feat

#82 [feat] 투표제출기능 제외, url없을때 지도연결버튼 제거
  app/api/user/appointments/[id]/vote/route.ts
  app/user/appointments/[id]/vote-place/page.tsx
  utils/supabase/client.ts
  utils/supabase/cookie.ts
  utils/supabase/cookieHelper.ts
Labels: ✨ feat

#83 Feat/signup
  app/(anon)/login/components/LoginForm.tsx
  app/api/auth/callback/route.ts
  app/api/auth/kakao-login-url/route.ts
  app/api/auth/logout/route.ts
  app/user/page.tsx
  application/usecases/auth/KakaoLoginUsecase.ts
  application/usecases/auth/SocialLoginUseCase.ts
  domain/repositories/AuthRepository.ts
  domain/repositories/UserRepository.ts
  infrastructure/repositories/SbAuthRepository.ts
  infrastructure/repositories/SbUserRepository.ts
Labels: 🐞 fix, ✨ feat, 🔧 refactor, remove, chore

#85 [feat] 로그인 후 토큰저장 방식 변경
  app/api/auth/callback/route.ts
  app/api/auth/login/route.ts
Labels: ✨ feat

#86 [style] 마이 페이지 아이콘 헤더 추가
  app/user/page.tsx
Labels: 🎨 style

#87 [fix] 로컬 스토리지 저장 제거
  app/(anon)/login/components/LoginForm.tsx
Labels: 🐞 fix

#88 [style] 약속 리스트 페이지 스크롤, 검색 수정
  app/user/appointments/Appointments.module.scss
  app/user/appointments/page.tsx
Labels: 🎨 style

#89 [fix] 카카오 로그아웃 후 다시 로그인 시 중복 업데이트 되는 현상 해결
  infrastructure/repositories/SbAuthRepository.ts
Labels: 🐞 fix

#90 [style] 헤더 링크 수정 및 데이터 유틸 함수 수정
  app/user/appointments/components/AppointmentCard.module.scss
  app/user/appointments/components/AppointmentCard.tsx
  app/user/appointments/page.tsx
  components/header/DropdownMenu.tsx
  components/header/IconHeader.tsx
  utils/dateUtils/dateUtils.ts
Labels: 🐞 fix, 🎨 style

#91 [feat] 로그인 시 토큰 저장 값 수정
  app/api/auth/callback/route.ts
  app/api/auth/login/route.ts
  app/api/auth/logout/route.ts
  package-lock.json
  package.json
Labels: ✨ feat

#92 [rename] usecase 폴더명앞에 Df 추가
  app/api/auth/callback/route.ts
  app/api/auth/check-nickname/route.ts
  app/api/auth/login/route.ts
  app/api/auth/logout/route.ts
  app/api/auth/signup/route.ts
  application/usecases/auth/DfLoginUsecase.ts
  application/usecases/auth/DfLogoutUsecase.ts
  application/usecases/auth/DfSignUpUseCase.ts
  application/usecases/auth/DfSocialLoginUseCase.ts
  application/usecases/auth/DfUserNicknameCheckUsecase.ts
  application/usecases/auth/dto/LoginResponseDto.ts
Labels: 🔧 refactor, rename

#95 [refactor] 마이 페이지 헤더 부분 수정 및 로그아웃 버튼 수정
  app/user/mypage.module.scss
  app/user/page.tsx
  components/header/Header.module.scss
  components/header/Header.tsx
  components/header/IconHeader.tsx
Labels: ✨ feat, 🎨 style, 🔧 refactor

#96 [feat] 쿠키에서 토큰을 가져와 userId를 구하는 방식 -> 쿠키에서 userId를 바로 받아오는 방식으로 변경
  app/api/auth/token/route.ts
  app/api/auth/user-id/route.ts
  app/api/user/appointments/[id]/vote/route.ts
  app/user/appointments/[id]/vote-place/page.tsx
  utils/supabase/client.ts
  utils/supabase/cookie.ts
Labels: ✨ feat

#97 [feat] 로그인 후 Supabase 자동 생성 토큰 삭제 추가
  app/api/auth/callback/route.ts
  app/api/auth/login/route.ts
Labels: ✨ feat

#98 [feat] 투표 후 멤버로 추가하는 기능 추가, 기존멤버일 경우 재투표 불가기능 추가
  app/api/user/appointments/[id]/time-vote/route.ts
  app/api/user/appointments/[id]/vote/route.ts
  app/user/appointments/[id]/vote-place/page.tsx
  application/usecases/vote/DfGetAppointmentTimeUsecase.ts.ts
  application/usecases/vote/DfGetPlaceVotesUsecase.ts
  application/usecases/vote/DfSubmitVoteUsecase.ts
  application/usecases/vote/dto/AppointmentTimeDto.ts
  application/usecases/vote/dto/PlaceVoteDto.ts
  application/usecases/vote/dto/VoteDto.ts
  domain/repositories/MemberRepository.ts
  infrastructure/repositories/SbMemberRepository.ts
Labels: ✨ feat

#99 [feat] 약속 리스트 페이지 DB 연결
  app/api/user/appointments/route.ts
  app/user/appointments/components/AppointmentCard.tsx
  app/user/appointments/components/AppointmentList.tsx
  app/user/appointments/page.tsx
  application/usecases/appointment/DfGetAppointmentCardUsecase.ts
  application/usecases/appointment/dto/AppointmentCardDto.ts
  components/header/Header.module.scss
  domain/entities/Member.ts
  domain/repositories/AppointmentRepository.ts
  domain/repositories/MemberRepository.ts
  domain/repositories/UserRepository.ts
  infrastructure/repositories/SbAppointmentRepository.ts
  infrastructure/repositories/SbMemberRepository.ts
  infrastructure/repositories/SbUserRepository.ts
  next.config.ts
Labels: ✨ feat, 🎨 style, ⚙ 개발 환경 세팅

#101 [feat] 자체 회원가입 코드 수정
  app/(anon)/signup/components/AuthForm.tsx
  app/api/auth/signup/route.ts
  application/usecases/auth/DfSignUpUseCase.ts
  domain/entities/User.ts
  domain/repositories/UserRepository.ts
  infrastructure/repositories/SbUserRepository.ts
  package-lock.json
  package.json
Labels: ✨ feat, 🔧 refactor

#103 [refactor] supabase 함수 사용하지 않고 구현하기
  app/api/auth/logout/route.ts
  domain/repositories/AuthRepository.ts
  infrastructure/repositories/SbAuthRepository.ts
Labels: 🔧 refactor

#104 [feat] 시간/장소 투표결과 불러오는 DfGetVoteResultUsecase.ts 작성
  app/api/user/appointments/[id]/vote-result/route.ts
  app/user/appointments/[id]/vote-result/components/TimeResult.tsx
  app/user/appointments/[id]/vote-result/page.tsx
  application/usecases/vote/DfGetVoteResultUsecase.ts
  domain/entities/Member.ts
  domain/repositories/AppointmentRepository.ts
  domain/repositories/PlaceVoteUserRepository.ts
  domain/repositories/TimeVoteUserRepository.ts
  infrastructure/repositories/SbAppointmentRepository.ts
  infrastructure/repositories/SbMemberRepository.ts
  infrastructure/repositories/SbPlaceVoteUserRepository.ts
  infrastructure/repositories/SbTimeVoteUserRepository.ts
  utils/dateUtils/dateUtils.ts
Labels: ✨ feat

#105 [feat] 방장 유무에따라 버튼 다르게 랜더링하는 기능 추가
  app/user/appointments/[id]/vote-result/page.tsx
  application/usecases/vote/DfGetVoteResultUsecase.ts
Labels: ✨ feat

#106 [feat] 약속확정 기능 추가
  app/api/user/appointments/[id]/confirm/route.ts
  app/user/appointments/[id]/confirm/complete/page.tsx
  app/user/appointments/[id]/confirm/page.tsx
  application/usecases/appointment/DfConfirmUseCase.ts
  domain/repositories/AppointmentRepository.ts
  infrastructure/repositories/SbAppointmentRepository.ts
Labels: ✨ feat

#107 [feat] 장소투표adapter수정, 시간투표페이지 사용하지 않는 변수 제거, PlaceVoteDto에 장소 id추가
  app/api/user/appointments/[id]/place-vote/route.ts
  app/user/appointments/[id]/vote-place/page.tsx
  app/user/appointments/[id]/vote-result/page.tsx
  app/user/appointments/[id]/vote-time/page.tsx
  application/usecases/vote/dto/PlaceVoteDto.ts
Labels: ✨ feat

#109 [feat] 로그인 시 에러메시지 변경
  app/api/auth/login/route.ts
  domain/repositories/AuthRepository.ts
  infrastructure/repositories/SbAuthRepository.ts
Labels: ✨ feat, 🔧 refactor

#110 [feat] access_token -> userId 저장
  app/api/auth/callback/route.ts
  app/api/auth/kakao-login-url/route.ts
  app/api/auth/login/route.ts
  app/api/auth/logout/route.ts
  app/api/auth/signup/route.ts
  application/usecases/auth/DfLoginUsecase.ts
  application/usecases/auth/dto/LoginResponseDto.ts
  domain/repositories/AuthRepository.ts
  infrastructure/repositories/SbAuthRepository.ts
  infrastructure/repositories/SbUserRepository.ts
  utils/auth/auth-utils.ts
Labels: ✨ feat, 🔧 refactor

#111 [style] loading spinner 추가
  app/user/appointments/[id]/confirm/page.tsx
  app/user/appointments/[id]/vote-place/page.tsx
  app/user/appointments/[id]/vote-result/page.tsx
  app/user/appointments/[id]/vote-time/page.tsx
Labels: ✨ feat

#112 [style] 움직이는 로고 제작
  app/(anon)/login/components/LogoWithTitle.tsx
  app/(anon)/page.tsx
  app/user/appointments/[id]/confirm/complete/complete.module.scss
  app/user/appointments/[id]/confirm/complete/page.tsx
  app/user/appointments/create/complete/page.tsx
  components/moongchi/Moongchi.module.scss
  components/moongchi/Moongchi.tsx
  package-lock.json
  package.json
Labels: 🎨 style

#114 Feat/information 약속정보 페이지 GET 통신 구현
  app/api/user/appointments/[id]/information/route.ts
  app/user/appointments/[id]/components/information/InformationDetail/InformationDetail.tsx
  app/user/appointments/[id]/components/information/NoticeDetail/NoticeDetail.tsx
  app/user/appointments/[id]/components/information/Participants/Participants.tsx
  app/user/appointments/[id]/information/page.tsx
  application/usecases/appointment/DfGetAppointmentCardUsecase.ts
  application/usecases/appointment/DfGetAppointmentInformationUsecase.ts
  application/usecases/appointment/dto/AppointmentInformationDto.ts
  domain/entities/Notice.ts
  domain/repositories/NoticeRepository.ts
  infrastructure/repositories/SbNoticeRepository.ts
Labels: ✨ feat

#116 [docs] 중복 파일 삭제 (CreateComplete)
  app/user/appointments/create/complete/page.tsx
Labels: 📃 docs

#117 [feat] 약속 생성 백엔드 및 Member entity 속성 추가
  app/api/user/appointments/create/route.ts
  app/api/user/appointments/route.ts
  app/user/appointments/create/components/complete.tsx
  app/user/appointments/create/components/place.tsx
  app/user/appointments/create/page.tsx
  application/usecases/appointment/DfCreateAppointmentUsecase.ts
  components/header/ArrowHeader.tsx
  domain/entities/Member.ts
  domain/repositories/AppointmentRepository.ts
  domain/repositories/PlaceVoteRepository.ts
  infrastructure/repositories/SbAppointmentRepository.ts
  infrastructure/repositories/SbMemberRepository.ts
  infrastructure/repositories/SbPlaceVoteRepository.ts
Labels: ✨ feat

#118 [refactor] vote관련 페이지 리펙토링 진행
  app/api/user/appointments/[id]/confirm/route.ts
  app/api/user/appointments/[id]/place-vote/route.ts
  app/api/user/appointments/[id]/time-vote/route.ts
  app/api/user/appointments/[id]/vote-result/route.ts
  app/api/user/appointments/[id]/vote/route.ts
  app/user/appointments/[id]/confirm/complete/complete.module.scss
  app/user/appointments/[id]/vote-place/page.tsx
  application/usecases/vote/DfGetAppointmentTimeUsecase.ts.ts
  application/usecases/vote/DfSubmitVoteUsecase.ts
  infrastructure/repositories/SbPlaceVoteUserRepository.ts
Labels: 🔧 refactor

#119 [feat] 약속 만들기 백엔드
  app/user/appointments/create/components/complete.tsx
  context/CreateAppointmentContext.tsx
Labels: ✨ feat

#120 [feat] 약속 리스트 userId 동적으로 변경
  app/api/user/appointments/route.ts
  app/user/appointments/page.tsx
  application/usecases/appointment/DfGetAppointmentCardUsecase.ts
  application/usecases/appointment/dto/AppointmentCardDto.ts
Labels: ✨ feat

#121 [feat] 약속 리스트 페이지 로딩 및 status 속성으로 필터링
  app/api/user/appointments/route.ts
  app/user/appointments/components/AppointmentCard.tsx
  app/user/appointments/page.tsx
  application/usecases/appointment/DfGetAppointmentCardUsecase.ts
  application/usecases/appointment/dto/AppointmentCardDto.ts
Labels: ✨ feat, 🎨 style

#122 [feat] my page supabase
  app/api/auth/callback/route.ts
  app/api/auth/login/route.ts
  app/api/auth/signup/route.ts
  app/api/user/[userId]/route.ts
  app/api/user/emojis/route.ts
  app/api/user/update-emoji/route.ts
  app/user/components/UserImage.tsx
  app/user/components/UserImageModalContent.module.scss
  app/user/components/UserImageModalContent.tsx
  app/user/components/UserName.tsx
  app/user/layout.tsx
  application/usecases/auth/DfLoginUsecase.ts
  application/usecases/auth/DfSignUpUseCase.ts
  application/usecases/auth/DfSocialLoginUseCase.ts
  application/usecases/auth/dto/LoginResponseDto.ts
  application/usecases/user/DfAllEmojisUsecase.ts
  application/usecases/user/DfUpdateEmojiUsecase.ts
  context/UserContext.tsx
  domain/repositories/AuthRepository.ts
  domain/repositories/UserRepository.ts
  infrastructure/repositories/SbAuthRepository.ts
  infrastructure/repositories/SbUserEmojiRepository.ts
  infrastructure/repositories/SbUserRepository.ts
  utils/auth/auth-utils.ts
  utils/auth/extractUserIdFromToken.ts
  utils/user/userEmojiAltText.ts
Labels: ✨ feat, 🎨 style, 🔧 refactor, remove, chore

#123 [feat] 투표상태에 따라 투표가능여부 결정하는 기능 추가, 시간 투표 로직 수정
  app/api/user/appointments/[id]/vote-result/route.ts
  app/api/user/appointments/[id]/vote/route.ts
  app/layout.tsx
  app/user/appointments/[id]/vote-place/page.tsx
  app/user/appointments/[id]/vote-time/page.tsx
  application/usecases/vote/DfGetVoteResultUsecase.ts
  application/usecases/vote/DfSubmitVoteUsecase.ts
  application/usecases/vote/dto/TimeVoteDto.ts
  application/usecases/vote/dto/VoteDto.ts
  domain/repositories/AppointmentRepository.ts
  domain/repositories/MemberRepository.ts
  domain/repositories/UserRepository.ts
  infrastructure/repositories/SbAppointmentRepository.ts
  infrastructure/repositories/SbMemberRepository.ts
  infrastructure/repositories/SbTimeVoteRepository.ts
  infrastructure/repositories/SbUserRepository.ts
Labels: ✨ feat

#126 [fix] conflict로 오류난거 수정
  app/api/user/appointments/[id]/vote-result/route.ts
  app/api/user/appointments/[id]/vote/route.ts
  app/layout.tsx
  app/user/appointments/[id]/vote-place/page.tsx
  app/user/appointments/[id]/vote-time/page.tsx
  application/usecases/vote/DfGetVoteResultUsecase.ts
  application/usecases/vote/DfSubmitVoteUsecase.ts
  application/usecases/vote/dto/TimeVoteDto.ts
  application/usecases/vote/dto/VoteDto.ts
  domain/repositories/AppointmentRepository.ts
  domain/repositories/MemberRepository.ts
  domain/repositories/UserRepository.ts
  infrastructure/repositories/SbAppointmentRepository.ts
  infrastructure/repositories/SbMemberRepository.ts
  infrastructure/repositories/SbTimeVoteRepository.ts
  infrastructure/repositories/SbUserRepository.ts
Labels: 🐞 fix

#127 [feat] route에서 하던 time-> time_id로 바꾸는 로직을 usecase에서 하도록 변경
  app/api/user/appointments/[id]/vote/route.ts
  application/usecases/vote/DfSubmitVoteUsecase.ts
  application/usecases/vote/dto/TimeVoteDto.ts
  application/usecases/vote/dto/VoteDto.ts
Labels: ✨ feat

#128 [feat] admin페이지 디자인 추가
  app/admin/appointments/appointments.module.scss
  app/admin/appointments/page.tsx
  app/admin/images/images.module.scss
  app/admin/images/page.tsx
  app/admin/layout.module.scss
  app/admin/layout.tsx
  app/admin/users/page.tsx
  app/admin/users/users.module.scss
  domain/entities/Admin.ts
Labels: ✨ feat, 🎨 style

#130 [feat] 약속 만들기 테이블 생성 로직 추가
  app/user/appointments/create/components/complete.module.scss
  app/user/appointments/create/components/complete.tsx
  app/user/appointments/create/components/place.tsx
  application/usecases/appointment/DfCreateAppointmentUsecase.ts
  context/CreateAppointmentContext.tsx
  domain/entities/PlaceVote.ts
  domain/repositories/PlaceVoteRepository.ts
  infrastructure/repositories/SbAppointmentRepository.ts
  infrastructure/repositories/SbPlaceVoteRepository.ts
Labels: ✨ feat, 🎨 style

#131 [feat] admin페이지-유저리스트불러오기, 유저삭제기능 구현
  app/admin/users/page.tsx
  app/admin/users/users.module.scss
  app/api/admin/users/[id]/route.ts
  app/api/admin/users/route.ts
  application/usecases/user/DfDeleteUserUsecase.ts
  application/usecases/user/DfGetAllUsersUsecase.ts
  application/usecases/user/dto/UserDeleteDto.ts
  application/usecases/user/dto/UserListDto.ts
  domain/repositories/UserRepository.ts
  infrastructure/repositories/SbUserRepository.ts
Labels: ✨ feat

#132 [feat] 약속 리스트 페이지 기능 오류 제어 및 Member Repository 추가
  app/api/user/appointments/route.ts
  app/api/user/member/route.ts
  app/user/appointments/components/AppointmentList.module.scss
  app/user/appointments/components/AppointmentList.tsx
  app/user/appointments/page.tsx
  application/usecases/appointment/DfGetAppointmentCardUsecase.ts
  application/usecases/appointment/DfGetAppointmentInformationUsecase.ts
  application/usecases/appointment/dto/AppointmentCardDto.ts
  application/usecases/member/DfGetMemberIsVote.ts
  domain/repositories/MemberRepository.ts
  infrastructure/repositories/SbMemberRepository.ts
Labels: 🐞 fix, ✨ feat, 🎨 style

#133 [feat] 약속 리스트 페이지 약속 종류에 따른 리다이렉트 추가
  app/user/appointments/components/AppointmentList.tsx
  application/usecases/member/DfGetMemberIsVote.ts
Labels: ✨ feat

#135 [feat] 기존 닉네임 변경시 변경하지 않도록 처리
  app/user/components/UserName.tsx
Labels: ✨ feat

#136 [feat] admin페이지- 약속관리기능 추가
  app/admin/appointments/appointments.module.scss
  app/admin/appointments/page.tsx
  app/admin/layout.module.scss
  app/admin/users/page.tsx
  app/admin/users/users.module.scss
  app/api/admin/appointments/[id]/route.ts
  app/api/admin/appointments/route.ts
  app/user/appointments/[id]/vote-place/page.tsx
  application/usecases/appointment/DfDeleteAppointmentUsecase.ts
  application/usecases/appointment/DfGetAllAppointmentsUsecase.ts
  application/usecases/appointment/dto/AppointmentListDto.ts
  domain/repositories/AppointmentRepository.ts
  infrastructure/repositories/SbAppointmentRepository.ts
Labels: ✨ feat

#137 [feat] 어드민페이지에서 유저삭제 route에서 usecase사용하도록 변경
  app/api/admin/users/[id]/route.ts
  application/usecases/user/DfDeleteUserUsecase.ts
Labels: ✨ feat

#139 [feat] 확인 버튼 누르기 전 한번 더 확인받기 추가
  app/user/components/DeleteAccountModalContent.tsx
Labels: ✨ feat

#143 [feat] 투표관련페이지 오류수정 및 로그인확인 로직 추가
  app/api/user/appointments/[id]/confirm/route.ts
  app/user/appointments/[id]/confirm/page.tsx
  app/user/appointments/[id]/vote-result/page.tsx
  app/user/appointments/[id]/vote-result/voteResult.module.scss
  app/user/appointments/[id]/vote-time/page.tsx
Labels: ✨ feat

#144 [fix] 약속 만들기 오류 해결
  app/user/appointments/create/components/place.tsx
  app/user/appointments/create/components/time.tsx
  context/CreateAppointmentContext.tsx
  domain/entities/Appointment.ts
  utils/dateUtils/dateUtils.ts
Labels: 🐞 fix, ✨ feat

#145 [feat] 약속 만들기 시간 선택 시 유효성 검사 추가
  app/user/appointments/create/components/time.tsx
Labels: ✨ feat

#146 [feat] 마이페이지 달력 연동하기
  app/api/user/user-appointments/route.ts
  app/user/components/MyCalendar.tsx
  application/usecases/appointment/DfGetUserAppointmentsUsecase.ts
  application/usecases/appointment/dto/UserAppointmentListDto.ts
Labels: ✨ feat

#147 [feat] 헤더 동적 닉네임으로 수정
  components/header/Header.tsx
Labels: ✨ feat

#148 [feat] 마이 페이지 상태에 따른 개수 표시
  app/user/components/AppointmentCount.tsx
  app/user/components/MyCalendar.tsx
  app/user/components/UserAppointmentCount.tsx
  app/user/page.tsx
  types/Event.ts
  utils/user/getEventsStatus.ts
Labels: ✨ feat, 🔧 refactor

#150 [feat] 시간투표-모바일환경드레그개선,헤더 레이아웃으로적용, 모바일환경 복사기능 개선
  app/user/appointments/[id]/confirm/complete/page.tsx
  app/user/appointments/[id]/confirm/confirm.module.scss
  app/user/appointments/[id]/vote-place/layout.tsx
  app/user/appointments/[id]/vote-place/page.tsx
  app/user/appointments/[id]/vote-place/votePlace.module.scss
  app/user/appointments/[id]/vote-result/components/PlaceResult.module.scss
  app/user/appointments/[id]/vote-result/components/TimeResult.module.scss
  app/user/appointments/[id]/vote-result/layout.tsx
  app/user/appointments/[id]/vote-result/page.tsx
  app/user/appointments/[id]/vote-result/voteResult.module.scss
  app/user/appointments/[id]/vote-time/layout.tsx
  app/user/appointments/[id]/vote-time/page.tsx
  app/user/appointments/[id]/vote-time/voteTime.module.scss
  utils/copy/copyUtils.ts
Labels: ✨ feat, 🎨 style

#151 [feat] 약속 리스트 페이지 카드에 복사 버튼 추가 등
  app/user/appointments/components/AppointmentCard.module.scss
  app/user/appointments/components/AppointmentCard.tsx
  app/user/appointments/create/components/complete.tsx
  components/header/ArrowHeader.tsx
  components/header/IconHeader.tsx
  components/header/components/DropdownMenu.module.scss
  components/header/components/DropdownMenu.tsx
  components/header/components/Header.module.scss
  components/header/components/Header.tsx
Labels: ✨ feat, 🔧 refactor

#152 [feat] 마이페이지 각 컴포넌트에 스켈레톤 UI 적용
  app/(anon)/login/components/LoginForm.tsx
  app/(anon)/login/components/LogoWithTitle.tsx
  app/user/components/MyCalendar.tsx
  app/user/components/UserImage.tsx
  app/user/components/UserImageModalContent.tsx
  app/user/components/user-skeleton/CalendarSkeleton.module.scss
  app/user/components/user-skeleton/CalendarSkeleton.tsx
  app/user/components/user-skeleton/EmojiSkeleton.module.scss
  app/user/components/user-skeleton/EmojiSkeleton.tsx
  app/user/components/user-skeleton/EmojisSkeleton.module.scss
  app/user/components/user-skeleton/EmojisSkeleton.tsx
  components/modal/Modal.tsx
Labels: ✨ feat, 🎨 style, 🔧 refactor, chore

#153 [style] 헤더 드롭 다운 위치 수정
  components/header/components/DropdownMenu.module.scss
Labels: 🎨 style

#155 [feat] page.tsx에서 하던 로그인 검사-> layout에 context로 검사, admin page 헤더추가
  app/admin/appointments/appointments.module.scss
  app/admin/images/images.module.scss
  app/admin/layout.module.scss
  app/admin/layout.tsx
  app/user/appointments/[id]/confirm/complete/page.tsx
  app/user/appointments/[id]/confirm/page.tsx
  app/user/appointments/[id]/vote-place/page.tsx
  app/user/appointments/[id]/vote-result/page.tsx
  app/user/appointments/[id]/vote-time/page.tsx
Labels: ✨ feat

#156 [sytle] css속성 glabalCSS속성으로 변경
  app/admin/appointments/appointments.module.scss
  app/admin/images/images.module.scss
  app/admin/layout.module.scss
  app/admin/users/users.module.scss
  app/user/appointments/[id]/confirm/confirm.module.scss
  app/user/appointments/[id]/vote-place/votePlace.module.scss
  app/user/appointments/[id]/vote-result/components/PlaceResult.module.scss
  app/user/appointments/[id]/vote-result/voteResult.module.scss
Labels: 🎨 style

#157 [feat] admin 페이지 권한 체크
  app/(anon)/page.tsx
  app/admin/appointments/page.tsx
  app/admin/images/page.tsx
  app/admin/users/page.tsx
  application/usecases/auth/DfSignUpUseCase.ts
  application/usecases/auth/DfSocialLoginUseCase.ts
  domain/entities/User.ts
  domain/repositories/UserRepository.ts
  infrastructure/repositories/SbUserRepository.ts
Labels: ✨ feat

#158 [Feat/information] 약속 상세 데이터 통신 구현
  app/api/user/appointments/[id]/gallery/route.ts
  app/api/user/appointments/[id]/information/route.ts
  app/api/user/appointments/[id]/settlement/route.ts
  app/user/appointments/[id]/components/detail/DetailTabMenu/DetailTabMenu.tsx
  app/user/appointments/[id]/components/gallery/galleryDetail/GalleryDetail.module.scss
  app/user/appointments/[id]/components/gallery/galleryDetail/GalleryDetail.tsx
  app/user/appointments/[id]/components/information/NoticeBox/NoticeBox.tsx
  app/user/appointments/[id]/components/information/NoticeDetail/NoticeDetail.tsx
  app/user/appointments/[id]/components/information/Participants/Participants.module.scss
  app/user/appointments/[id]/components/information/Participants/Participants.tsx
  app/user/appointments/[id]/components/settlement/SettlementDetail/SettlementDetail.module.scss
  app/user/appointments/[id]/components/settlement/SettlementDetail/SettlementDetail.tsx
  app/user/appointments/[id]/components/settlement/SettlementModalContent/SettlementModalContent.tsx
  app/user/appointments/[id]/components/settlement/SettlementModalNew/SettlementModalNew.tsx
  app/user/appointments/[id]/gallery/gallery.module.scss
  app/user/appointments/[id]/gallery/page.tsx
  app/user/appointments/[id]/information/information.module.scss
  app/user/appointments/[id]/information/page.tsx
  app/user/appointments/[id]/settlement/page.tsx
  app/user/appointments/[id]/settlement/settlement.module.scss
  application/usecases/appointment/DfCreateNotionUsecase.ts
  application/usecases/appointment/DfCreateSettlementUsecase.ts
  application/usecases/appointment/DfDeleteNotionUseCase.ts
  application/usecases/appointment/DfGetAppointmentInformationUsecase.ts
  application/usecases/appointment/DfGetSettlementUsecase.ts
  application/usecases/appointment/DfUpdateNotionUseCase.ts
  application/usecases/appointment/DfUpdateSettlementUsecase.ts
  application/usecases/appointment/dto/AppointmentInformationDto.ts
  application/usecases/appointment/dto/NoticeDto.ts
  application/usecases/appointment/dto/SettlementDto.ts
  application/usecases/appointmentImage/DfCreateImageUsecase.ts
  application/usecases/appointmentImage/DfGetImageUsecase.ts
  application/usecases/appointmentImage/dto/ImageListDto.ts
  components/button/Button.tsx
  domain/entities/Payments.ts
  domain/entities/PaymentsDetail.ts
  domain/repositories/AppointmentImageRepository.ts
  domain/repositories/PaymentsDetailRepository.ts
  domain/repositories/PaymentsRepository.ts
  infrastructure/repositories/SbAppointmentImageRepository.ts
  infrastructure/repositories/SbNoticeRepository.ts
  infrastructure/repositories/SbPaymentsDetailRepository.ts
  infrastructure/repositories/SbPaymentsRepository.ts
Labels: ✨ feat

#159 [fix] user타입 변경
  app/admin/images/page.tsx
  domain/entities/User.ts
Labels: 🐞 fix

#160 [feat] admin 페이지 권한 체크 함수 분리
  app/admin/appointments/page.tsx
  app/admin/images/page.tsx
  app/admin/users/page.tsx
  hooks/useAdminCheck.ts
Labels: 🔧 refactor

#161 [refactor] api에서 사용하지 않는 request 코드 제거
  app/admin/appointments/page.tsx
  app/admin/hooks/useAdminCheck.ts
  app/admin/images/page.tsx
  app/admin/users/page.tsx
  app/api/auth/user-id/route.ts
  app/api/user/emojis/route.ts
Labels: 🔧 refactor

#162 [refactor] fetch요청 POST -> PATCH로 변경
  app/api/user/update-emoji/route.ts
  app/user/components/UserImageModalContent.tsx
Labels: 🔧 refactor

#164 [refactor] 닉네임 변경 API 호출 로직 분리
  app/user/components/UserName.tsx
Labels: 🔧 refactor

#165 [refactor] 중복되는 함수를 getAppointmentCount 함수로 분리
  app/user/components/UserAppointmentCount.tsx
Labels: 🔧 refactor

#166 [refactor] 약속 리스트 페이지 코드 리팩토링
  app/api/user/check-appointment-entry/route.ts
  app/user/appointments/Appointments.module.scss
  app/user/appointments/components/EntryAppointmentModal.module.scss
  app/user/appointments/components/EntryAppointmentModal.tsx
  app/user/appointments/hooks/useAppointments.ts
  app/user/appointments/hooks/useEnrtyAppointmentModal.ts
  app/user/appointments/page.tsx
Labels: ✨ feat, 🎨 style, 🔧 refactor

#167 [fix] 닉네임 중복 에러 처리
  app/api/user/update-nickname/route.ts
  app/user/components/UserName.tsx
Labels: 🐞 fix

#169 [refactor] useLogin으로 비즈니스 로직 분리
  app/(anon)/login/components/LoginForm.tsx
  app/(anon)/login/hooks/useLogin.ts
Labels: 🔧 refactor

#170 [feat] 약속관련페이지에서 멤버인지 확인하는 기능 추가
  app/api/user/appointments/[id]/route.ts
  app/user/appointments/[id]/(member)/components/const/banks.ts
  app/user/appointments/[id]/(member)/components/detail/DetailTabMenu/DetailTabMenu.module.scss
  app/user/appointments/[id]/(member)/components/detail/DetailTabMenu/DetailTabMenu.tsx
  app/user/appointments/[id]/(member)/components/detail/dummyData/detailDummyData.ts
  app/user/appointments/[id]/(member)/components/detail/types/detailTypes.ts
  app/user/appointments/[id]/(member)/components/gallery/galleryDetail/GalleryDetail.module.scss
  app/user/appointments/[id]/(member)/components/gallery/galleryDetail/GalleryDetail.tsx
  app/user/appointments/[id]/(member)/components/information/InformationDetail/InformationDetail.module.scss
  app/user/appointments/[id]/(member)/components/information/InformationDetail/InformationDetail.tsx
  app/user/appointments/[id]/(member)/components/information/NoticeBox/NoticeBox.module.scss
  app/user/appointments/[id]/(member)/components/information/NoticeBox/NoticeBox.tsx
  app/user/appointments/[id]/(member)/components/information/NoticeDetail/NoticeDetail.module.scss
  app/user/appointments/[id]/(member)/components/information/NoticeDetail/NoticeDetail.tsx
  app/user/appointments/[id]/(member)/components/information/Participants/Participants.module.scss
  app/user/appointments/[id]/(member)/components/information/Participants/Participants.tsx
  app/user/appointments/[id]/(member)/components/settlement/SettlementDetail/SettlementDetail.module.scss
  app/user/appointments/[id]/(member)/components/settlement/SettlementDetail/SettlementDetail.tsx
  app/user/appointments/[id]/(member)/components/settlement/SettlementModalContent/SettlementModalContent.tsx
  app/user/appointments/[id]/(member)/components/settlement/SettlementModalNew/SettlementModalNew.tsx
  app/user/appointments/[id]/(member)/confirm/complete/complete.module.scss
  app/user/appointments/[id]/(member)/confirm/complete/page.tsx
  app/user/appointments/[id]/(member)/confirm/confirm.module.scss
  app/user/appointments/[id]/(member)/confirm/page.tsx
  app/user/appointments/[id]/(member)/gallery/gallery.module.scss
  app/user/appointments/[id]/(member)/gallery/page.tsx
  app/user/appointments/[id]/(member)/information/information.module.scss
  app/user/appointments/[id]/(member)/information/page.tsx
  app/user/appointments/[id]/(member)/layout.tsx
  app/user/appointments/[id]/(member)/settlement/page.tsx
  app/user/appointments/[id]/(member)/settlement/settlement.module.scss
  app/user/appointments/[id]/(member)/vote-place/layout.tsx
  app/user/appointments/[id]/(member)/vote-place/page.tsx
  app/user/appointments/[id]/(member)/vote-place/votePlace.module.scss
  app/user/appointments/[id]/(member)/vote-result/components/PlaceResult.module.scss
  app/user/appointments/[id]/(member)/vote-result/components/PlaceResult.tsx
  app/user/appointments/[id]/(member)/vote-result/components/TimeResult.module.scss
  app/user/appointments/[id]/(member)/vote-result/components/TimeResult.tsx
  app/user/appointments/[id]/(member)/vote-result/layout.tsx
  app/user/appointments/[id]/(member)/vote-result/page.tsx
  app/user/appointments/[id]/(member)/vote-result/voteResult.module.scss
  app/user/appointments/[id]/(member)/vote-time/layout.tsx
  app/user/appointments/[id]/(member)/vote-time/page.tsx
  app/user/appointments/[id]/(member)/vote-time/voteTime.module.scss
  application/usecases/member/DfIsMemberUsecase.ts
  application/usecases/vote/DfGetVoteResultUsecase.ts
Labels: ✨ feat

#171 [refactor] 약속 만들기 페이지 리팩토링
  app/user/appointments/create/components/createComplete.module.scss
  app/user/appointments/create/components/createComplete.tsx
  app/user/appointments/create/components/createInformation.module.scss
  app/user/appointments/create/components/createInformation.tsx
  app/user/appointments/create/components/createPlace.module.scss
  app/user/appointments/create/components/createPlace.tsx
  app/user/appointments/create/components/createTime.module.scss
  app/user/appointments/create/components/createTime.tsx
  app/user/appointments/create/components/information.tsx
  app/user/appointments/create/components/time.tsx
  app/user/appointments/create/hooks/useCreateComplete.ts
  app/user/appointments/create/hooks/useCreateInformaion.ts
  app/user/appointments/create/hooks/useCreatePlace.ts
  app/user/appointments/create/hooks/useCreateTime.ts
  app/user/appointments/create/page.tsx
  utils/dateUtils/dateUtils.ts
Labels: ✨ feat, 🔧 refactor

#172 [style] 시간투표 그리드 위치조정, 장소투표 카운트추가
  app/api/user/appointments/[id]/vote/route.ts
  app/user/appointments/[id]/(member)/confirm/confirm.module.scss
  app/user/appointments/[id]/(member)/confirm/page.tsx
  app/user/appointments/[id]/(member)/vote-result/components/PlaceResult.module.scss
  app/user/appointments/[id]/(member)/vote-result/components/PlaceResult.tsx
  app/user/appointments/[id]/(member)/vote-result/components/TimeResult.module.scss
  app/user/appointments/[id]/(member)/vote-result/page.tsx
  app/user/appointments/[id]/(member)/vote-result/voteResult.module.scss
  app/user/appointments/[id]/(member)/vote-time/voteTime.module.scss
Labels: 🎨 style

#174 [refactor] 회원가입 비즈니스 로직 분리
  app/(anon)/signup/components/AuthForm.tsx
  app/(anon)/signup/hooks/useCheckNickname.ts
  app/(anon)/signup/hooks/useForm.ts
  app/(anon)/signup/hooks/useSubmitSignup.ts
Labels: 🔧 refactor

#175 [feat] 특정약속에서 멤버삭제하는기능 추가
  app/api/user/appointments/[id]/information/member/route.ts
  app/api/user/appointments/[id]/information/route.ts
  app/user/appointments/[id]/(member)/information/page.tsx
Labels: ✨ feat

#176 [refactor] 약속 참여 페이지 리팩토링
  app/user/appointments/[id]/entry/hooks/useEntry.ts
  app/user/appointments/[id]/entry/page.tsx
  app/user/appointments/components/AppointmentCard.tsx
  app/user/appointments/create/hooks/useCreateComplete.ts
  utils/copy/copyUtils.ts
Labels: ✨ feat, 🔧 refactor

#177 [refactor] 약속 만들기 페이지 리팩토링
  app/user/appointments/create/hooks/useCreateComplete.ts
  app/user/appointments/create/hooks/useCreateInformaion.ts
  context/CreateAppointmentContext.tsx
Labels: ✨ feat, 🔧 refactor

#178 [feat] arrow function으로 교체
  app/admin/appointments/page.tsx
  app/admin/images/page.tsx
  app/admin/layout.tsx
  app/admin/users/page.tsx
  app/api/admin/appointments/[id]/route.ts
  app/api/admin/appointments/route.ts
  app/api/admin/images/[id]/route.ts
  app/api/admin/images/route.ts
  app/api/admin/users/[id]/route.ts
  app/api/admin/users/route.ts
  app/api/user/appointments/[id]/confirm/route.ts
  app/api/user/appointments/[id]/place-vote/route.ts
  app/api/user/appointments/[id]/route.ts
  app/api/user/appointments/[id]/time-vote/route.ts
  app/api/user/appointments/[id]/vote-result/route.ts
  app/api/user/appointments/[id]/vote/route.ts
  app/user/appointments/[id]/(member)/confirm/page.tsx
  app/user/appointments/[id]/(member)/layout.tsx
Labels: ✨ feat

#179 [feat] 관리자 페이지 권한 체크 기능 구현
  app/admin/hooks/useAdminCheck.ts
  app/api/admin/route.ts
  app/api/auth/login/route.ts
  application/usecases/auth/dto/LoginResponseDto.ts
  application/usecases/user/DfGetUserTypeUsecase.ts
  application/usecases/user/dto/GetUserTypeDto.ts
  infrastructure/repositories/SbAuthRepository.ts
  infrastructure/repositories/SbUserRepository.ts
Labels: ✨ feat, 🔧 refactor

#180 [style] 버튼 크기 수정 및 컨테이너 수정
  app/(anon)/page.module.scss
Labels: 🎨 style

#181 [style] mediaquery 추가
  app/user/components/AppointmentCount.module.scss
  app/user/components/UserAppointmentCount.module.scss
Labels: 🎨 style

#182 [feat] 관리자 페이지 로그인 되지 않은 유저 에러처리
  app/admin/hooks/useAdminCheck.ts
Labels: ✨ feat

#183 [chore] 필요하지 않은 모듈 제거
  app/(anon)/login/components/LoginForm.tsx
  app/(anon)/page.tsx
  app/(anon)/signup/page.tsx
Labels: chore

#184 [feat] admin이 약속페이지에 접근할 수 있도록 수정
  app/api/user/appointments/[id]/route.ts
  app/user/appointments/[id]/(member)/layout.tsx
  application/usecases/appointment/DfAccessUsecase.ts
  application/usecases/member/DfIsMemberUsecase.ts
  application/usecases/vote/DfSubmitVoteUsecase.ts
  application/usecases/vote/dto/AccessDto.ts
  domain/entities/Admin.ts
  domain/repositories/UserRepository.ts
  infrastructure/repositories/SbUserRepository.ts
  utils/supabase/client.ts
Labels: ✨ feat

#187 [fix] route.ts에서 id값 못받아오는 오류 수정
  app/api/admin/appointments/[id]/route.ts
  app/api/admin/images/[id]/route.ts
  app/api/user/appointments/[id]/confirm/route.ts
  app/api/user/appointments/[id]/place-vote/route.ts
  app/api/user/appointments/[id]/route.ts
  app/api/user/appointments/[id]/time-vote/route.ts
  app/api/user/appointments/[id]/vote-result/route.ts
Labels: 🐞 fix

#188 [chore] console.error -> console.log로 변경
  app/api/user/appointments/[id]/confirm/route.ts
  app/api/user/appointments/[id]/place-vote/route.ts
  app/api/user/appointments/[id]/vote-result/route.ts
  app/api/user/appointments/[id]/vote/route.ts
  app/api/user/route.ts
  app/user/appointments/[id]/(member)/confirm/page.tsx
  app/user/appointments/[id]/(member)/vote-place/page.tsx
  app/user/appointments/[id]/(member)/vote-result/page.tsx
Labels: chore

#189 [fix] error message 변경
  app/(anon)/login/components/KakaoLogin.tsx
  app/(anon)/page.tsx
  app/(anon)/signup/components/EmailInputField.module.scss
  app/api/auth/callback/route.ts
  app/api/auth/check-nickname/route.ts
  app/api/auth/logout/route.ts
  app/api/auth/signup/route.ts
  app/api/user/[userId]/route.ts
  context/UserContext.tsx
Labels: 🐞 fix, 🔧 refactor, chore

#190 배포용 merge
  app/(anon)/login/components/KakaoLogin.tsx
  app/(anon)/page.tsx
  app/(anon)/signup/components/EmailInputField.module.scss
  app/api/auth/callback/route.ts
  app/api/auth/check-nickname/route.ts
  app/api/auth/logout/route.ts
  app/api/auth/signup/route.ts
  app/api/user/[userId]/route.ts
  app/api/user/appointments/[id]/confirm/route.ts
  app/api/user/appointments/[id]/place-vote/route.ts
  app/api/user/appointments/[id]/vote-result/route.ts
  app/api/user/appointments/[id]/vote/route.ts
  app/api/user/route.ts
  app/user/appointments/[id]/(member)/confirm/page.tsx
  app/user/appointments/[id]/(member)/vote-place/page.tsx
  app/user/appointments/[id]/(member)/vote-result/page.tsx
  context/UserContext.tsx
Labels: 🌏 배포

#191 [fix] import 오타 수정
  app/user/appointments/[id]/(member)/gallery/page.tsx
Labels: 🐞 fix

#192 배포용 merge
  app/user/appointments/[id]/(member)/gallery/page.tsx
Labels: 🌏 배포

#193 [fix] 의존성 배열에 onAppointmentsFetch 추가
  app/user/components/MyCalendar.tsx
Labels: 🐞 fix

#194 [fix] 배포중 경고 오류 수정
  app/api/user/appointments/create/route.ts
  app/user/appointments/[id]/entry/hooks/useEntry.ts
  app/user/appointments/components/AppointmentCard.module.scss
  app/user/appointments/create/components/createPlace.module.scss
  app/user/appointments/hooks/useAppointments.ts
Labels: 🐞 fix

#195 [refactor] autoprefixer 관련리팩토링,[id] 동적 경로에서 params 처리 문제관련 리팩토링
  app/api/admin/appointments/[id]/route.ts
  app/api/admin/images/[id]/route.ts
  app/api/user/appointments/[id]/confirm/route.ts
  app/api/user/appointments/[id]/place-vote/route.ts
  app/api/user/appointments/[id]/route.ts
  app/api/user/appointments/[id]/time-vote/route.ts
  app/api/user/appointments/[id]/vote-result/route.ts
  app/api/user/appointments/[id]/vote/route.ts
  app/api/user/route.ts
  app/user/appointments/[id]/(member)/confirm/confirm.module.scss
  app/user/appointments/[id]/(member)/vote-result/components/PlaceResult.module.scss
  application/usecases/appointment/DfDeleteAppointmentUsecase.ts
  application/usecases/appointmentImage/DfDeleteImageUsecase.ts
  domain/repositories/AppointmentImageRepository.ts
  domain/repositories/AppointmentRepository.ts
  infrastructure/repositories/SbAppointmentImageRepository.ts
  infrastructure/repositories/SbAppointmentRepository.ts
Labels: 🔧 refactor

#196 배포 에러 해결
  app/api/admin/appointments/[id]/route.ts
  app/api/admin/images/[id]/route.ts
  app/api/user/appointments/[id]/confirm/route.ts
  app/api/user/appointments/[id]/place-vote/route.ts
  app/api/user/appointments/[id]/route.ts
  app/api/user/appointments/[id]/time-vote/route.ts
  app/api/user/appointments/[id]/vote-result/route.ts
  app/api/user/appointments/[id]/vote/route.ts
  app/api/user/appointments/create/route.ts
  app/api/user/route.ts
  app/user/appointments/[id]/(member)/confirm/confirm.module.scss
  app/user/appointments/[id]/(member)/vote-result/components/PlaceResult.module.scss
  app/user/appointments/[id]/entry/hooks/useEntry.ts
  app/user/appointments/components/AppointmentCard.module.scss
  app/user/appointments/create/components/createPlace.module.scss
  app/user/appointments/hooks/useAppointments.ts
  app/user/components/MyCalendar.tsx
  application/usecases/appointment/DfDeleteAppointmentUsecase.ts
  application/usecases/appointmentImage/DfDeleteImageUsecase.ts
  domain/repositories/AppointmentImageRepository.ts
  domain/repositories/AppointmentRepository.ts
  infrastructure/repositories/SbAppointmentImageRepository.ts
  infrastructure/repositories/SbAppointmentRepository.ts
Labels: 🌏 배포

#198 [fix] NextResponse-> NextRequest
  app/api/admin/appointments/[id]/route.ts
  app/api/admin/images/[id]/route.ts
  app/api/user/appointments/[id]/confirm/route.ts
  app/api/user/appointments/[id]/place-vote/route.ts
  app/api/user/appointments/[id]/route.ts
  app/api/user/appointments/[id]/time-vote/route.ts
  app/api/user/appointments/[id]/vote-result/route.ts
  app/api/user/route.ts
Labels: 🐞 fix

#200 [feat] route NextRequest로 변경
  app/api/user/appointments/create/route.ts
  app/api/user/appointments/route.ts
  app/user/appointments/hooks/useAppointments.ts
Labels: ✨ feat

#201 deploy merge
  app/api/admin/appointments/[id]/route.ts
  app/api/admin/images/[id]/route.ts
  app/api/user/appointments/[id]/confirm/route.ts
  app/api/user/appointments/[id]/gallery/route.ts
  app/api/user/appointments/[id]/information/member/route.ts
  app/api/user/appointments/[id]/place-vote/route.ts
  app/api/user/appointments/[id]/route.ts
  app/api/user/appointments/[id]/time-vote/route.ts
  app/api/user/appointments/[id]/vote-result/route.ts
  app/api/user/appointments/create/route.ts
  app/api/user/appointments/route.ts
  app/api/user/route.ts
  app/user/appointments/[id]/(member)/components/information/InformationDetail/InformationDetail.tsx
  app/user/appointments/[id]/(member)/components/information/NoticeBox/NoticeBox.tsx
  app/user/appointments/[id]/(member)/components/information/NoticeDetail/NoticeDetail.module.scss
  app/user/appointments/[id]/(member)/components/information/NoticeDetail/NoticeDetail.tsx
  app/user/appointments/[id]/(member)/gallery/page.tsx
  app/user/appointments/[id]/(member)/information/information.module.scss
  app/user/appointments/[id]/(member)/information/page.tsx
  app/user/appointments/[id]/(member)/settlement/page.tsx
  app/user/appointments/[id]/(member)/settlement/settlement.module.scss
  app/user/appointments/hooks/useAppointments.ts
  application/usecases/appointment/DfCreateSettlementUsecase.ts
  application/usecases/appointment/DfDeleteMemberUsecase.ts
  application/usecases/appointment/DfUpdateNoticeUsecase.ts
  infrastructure/repositories/SbNoticeRepository.ts
Labels: 🌏 배포

#208 Fix/route
  app/api/admin/appointments/[id]/route.ts
  app/api/admin/images/[id]/route.ts
  app/api/admin/users/[id]/route.ts
  app/api/auth/callback/route.ts
  app/api/auth/kakao-user/route.ts
  app/api/user/[userId]/route.ts
  app/api/user/appointments/[id]/confirm/route.ts
  app/api/user/appointments/[id]/gallery/route.ts
  app/api/user/appointments/[id]/information/member/route.ts
  app/api/user/appointments/[id]/place-vote/route.ts
  app/api/user/appointments/[id]/route.ts
  app/api/user/appointments/[id]/time-vote/route.ts
  app/api/user/appointments/[id]/vote-result/route.ts
  app/api/user/appointments/[id]/vote/route.ts
  app/api/user/user-appointments/route.ts
  application/usecases/vote/dto/PlaceVoteDto.ts
Labels: 🐞 fix

#211 [fix] 멤버인지 확인하는 route 오류 수정
  app/api/user/appointments/[id]/route.ts
  infrastructure/repositories/SbMemberRepository.ts
Labels: 🐞 fix

#214 [style] 버튼 border-radius 수정
  components/button/Button.module.scss
Labels: 🎨 style

#215 Develop merge to main (console.Error->console.log)
  app/admin/hooks/useAdminCheck.ts
  app/api/admin/appointments/[id]/route.ts
  app/api/admin/images/[id]/route.ts
  app/api/admin/route.ts
  app/api/admin/users/[id]/route.ts
  app/api/auth/login/route.ts
  app/api/user/appointments/[id]/confirm/route.ts
  app/api/user/appointments/[id]/gallery/route.ts
  app/api/user/appointments/[id]/information/member/route.ts
  app/api/user/appointments/[id]/information/route.ts
  app/api/user/appointments/[id]/settlement/route.ts
  app/api/user/appointments/create/route.ts
  app/user/appointments/[id]/(member)/components/information/NoticeBox/NoticeBox.tsx
  app/user/appointments/[id]/(member)/components/information/NoticeDetail/NoticeDetail.tsx
  app/user/appointments/[id]/(member)/components/settlement/SettlementModalContent/SettlementModalContent.tsx
  app/user/appointments/[id]/(member)/components/settlement/SettlementModalNew/SettlementModalNew.tsx
  app/user/appointments/[id]/(member)/gallery/page.tsx
  app/user/appointments/[id]/(member)/information/page.tsx
  app/user/appointments/[id]/(member)/layout.tsx
  app/user/appointments/[id]/(member)/settlement/page.tsx
  app/user/appointments/[id]/(member)/vote-place/page.tsx
  app/user/appointments/[id]/(member)/vote-time/page.tsx
  app/user/components/DeleteAccountModalContent.tsx
  app/user/components/UserImageModalContent.tsx
  application/usecases/appointment/DfDeleteMemberUsecase.ts
  application/usecases/appointment/DfDeleteNoticeUsecase.ts
  components/button/Button.module.scss
  components/header/components/DropdownMenu.tsx
  components/header/components/Header.tsx
  context/CreateAppointmentContext.tsx
  infrastructure/repositories/SbAppointmentImageRepository.ts
  infrastructure/repositories/SbAppointmentRepository.ts
  infrastructure/repositories/SbMemberRepository.ts
  infrastructure/repositories/SbNoticeRepository.ts
  infrastructure/repositories/SbPaymentsDetailRepository.ts
  infrastructure/repositories/SbPaymentsRepository.ts
  infrastructure/repositories/SbPlaceVoteUserRepository.ts
  infrastructure/repositories/SbUserRepository.ts
  utils/auth/extractUserIdFromToken.ts
Labels: 🎨 style, chore

#216 [style] ui 반응형 작업 로그인, 마이페이지
  app/(anon)/login/components/KakaoLogin.module.scss
  app/(anon)/login/login.module.scss
  app/user/components/AppointmentCount.module.scss
  app/user/components/UserAppointmentCount.module.scss
  app/user/components/UserImage.module.scss
  app/user/components/UserProfile.module.scss
  app/user/components/UserProfile.tsx
  app/user/mypage.module.scss
  app/user/page.tsx
  components/moongchi/Moongchi.module.scss
Labels: 🎨 style, remove

#218 [style] ui/modal
  app/user/components/DeleteAccountModalContent.tsx
  components/modal/Modal.module.scss
Labels: 🎨 style

#219 develop to main merge
  app/user/components/DeleteAccountModalContent.tsx
  components/modal/Modal.module.scss
Labels: 🌏 배포

#220 [feat] openGraph 추가
  app/layout.tsx
  public/og-image.png
Labels: ✨ feat

#221 Develop merge to main (open graph 추가)
  app/layout.tsx
  public/og-image.png
Labels: ✨ feat

#222 [style] 반응형을 위해 미디어쿼리 추가
  app/user/appointments/[id]/(member)/vote-result/components/TimeResult.module.scss
  app/user/appointments/[id]/(member)/vote-result/voteResult.module.scss
  app/user/appointments/[id]/(member)/vote-time/voteTime.module.scss
Labels: 🎨 style

#223 [style] 마이페이지 UI 수정
  app/user/components/AppointmentCount.module.scss
  app/user/components/MyCalendar.scss
  app/user/components/UserImage.module.scss
  app/user/components/UserImage.tsx
  app/user/components/UserName.module.scss
  app/user/components/UserName.tsx
  app/user/mypage.module.scss
Labels: ✨ feat, 🎨 style

#224 [style] 마이 페이지 약속 개수 컴포넌트 스타일 수정
  app/globals.css
  app/user/components/AppointmentCount.module.scss
Labels: 🎨 style, ⚙ 개발 환경 세팅

#225 [style] admin페이지 약속상태 컬러 변경
  app/admin/appointments/appointments.module.scss
Labels: 🎨 style

#226 [UI/information] 약속 상세 스타일 수정
  README.md
  app/user/appointments/[id]/(member)/components/gallery/galleryDetail/GalleryDetail.module.scss
  app/user/appointments/[id]/(member)/components/information/InformationDetail/InformationDetail.module.scss
  app/user/appointments/[id]/(member)/components/information/InformationDetail/InformationDetail.tsx
  app/user/appointments/[id]/(member)/components/information/NoticeBox/NoticeBox.module.scss
  app/user/appointments/[id]/(member)/components/information/NoticeDetail/NoticeDetail.module.scss
  app/user/appointments/[id]/(member)/components/information/Participants/Participants.tsx
  app/user/appointments/[id]/(member)/gallery/gallery.module.scss
Labels: 🎨 style

#227 [feat] pwa설정
  app/layout.tsx
  next.config.mjs
  next.config.ts
  package-lock.json
  package.json
  public/icons/icon-192x192.png
  public/icons/icon-512x512.png
  public/manifest.json
  public/screenshots/home-desktop.png
  public/screenshots/home-mobile.png
  public/sw.js
  public/workbox-4754cb34.js
  tsconfig.json
Labels: ✨ feat

#228 [feat] 약속 필터링 기능 추가
  app/user/components/AppointmentCount.module.scss
  app/user/components/MyCalendar.tsx
  app/user/components/UserAppointmentCount.module.scss
  app/user/components/UserAppointmentCount.tsx
  app/user/page.tsx
Labels: ✨ feat, 🎨 style

#230 [style] 약속 리스트, 약속 참여 페이지 수정
  app/user/appointments/Appointments.module.scss
  app/user/appointments/[id]/entry/entry.module.scss
  app/user/appointments/[id]/entry/hooks/useEntry.ts
  app/user/appointments/[id]/entry/page.tsx
  app/user/appointments/components/AppointmentCard.module.scss
  app/user/appointments/components/AppointmentCard.tsx
  app/user/appointments/components/EntryAppointmentModal.tsx
  app/user/appointments/create/components/createPlace.tsx
  app/user/appointments/hooks/useEntryAppointmentModal.ts
  components/button/Button.tsx
  components/input-filed/InputFiled.tsx
  utils/dateUtils/dateUtils.ts
Labels: 🐞 fix, ✨ feat, 🎨 style

#231 develop merge to main
  README.md
  app/admin/appointments/appointments.module.scss
  app/globals.css
  app/layout.tsx
  app/user/appointments/Appointments.module.scss
  app/user/appointments/[id]/(member)/components/gallery/galleryDetail/GalleryDetail.module.scss
  app/user/appointments/[id]/(member)/components/information/InformationDetail/InformationDetail.module.scss
  app/user/appointments/[id]/(member)/components/information/InformationDetail/InformationDetail.tsx
  app/user/appointments/[id]/(member)/components/information/NoticeBox/NoticeBox.module.scss
  app/user/appointments/[id]/(member)/components/information/NoticeDetail/NoticeDetail.module.scss
  app/user/appointments/[id]/(member)/components/information/Participants/Participants.tsx
  app/user/appointments/[id]/(member)/gallery/gallery.module.scss
  app/user/appointments/[id]/(member)/vote-result/components/TimeResult.module.scss
  app/user/appointments/[id]/(member)/vote-result/voteResult.module.scss
  app/user/appointments/[id]/(member)/vote-time/voteTime.module.scss
  app/user/appointments/[id]/entry/entry.module.scss
  app/user/appointments/[id]/entry/hooks/useEntry.ts
  app/user/appointments/[id]/entry/page.tsx
  app/user/appointments/components/AppointmentCard.module.scss
  app/user/appointments/components/AppointmentCard.tsx
  app/user/appointments/components/EntryAppointmentModal.tsx
  app/user/appointments/create/components/createPlace.tsx
  app/user/appointments/hooks/useEntryAppointmentModal.ts
  app/user/components/AppointmentCount.module.scss
  app/user/components/MyCalendar.scss
  app/user/components/MyCalendar.tsx
  app/user/components/UserAppointmentCount.module.scss
  app/user/components/UserAppointmentCount.tsx
  app/user/components/UserImage.module.scss
  app/user/components/UserImage.tsx
  app/user/components/UserName.module.scss
  app/user/components/UserName.tsx
  app/user/mypage.module.scss
  app/user/page.tsx
  components/button/Button.tsx
  components/input-filed/InputFiled.tsx
  next.config.mjs
  next.config.ts
  package-lock.json
  package.json
  public/icons/icon-192x192.png
  public/icons/icon-512x512.png
  public/manifest.json
  public/screenshots/home-desktop.png
  public/screenshots/home-mobile.png
  public/sw.js
  public/workbox-4754cb34.js
  tsconfig.json
  utils/dateUtils/dateUtils.ts
Labels: 🌏 배포

#232 [fix] pwa설정중 webpack관련 오류 수정, 투표결과페이지 미디어쿼리 설정
  app/user/appointments/[id]/(member)/vote-result/voteResult.module.scss
  next.config.mjs
Labels: 🐞 fix, 🎨 style

#233 Develop merge to main
  app/user/appointments/[id]/(member)/vote-result/voteResult.module.scss
  next.config.mjs
Labels: 🌏 배포

#234 [fix] 약속나가기 오류
  app/api/user/appointments/[id]/information/member/route.ts
  app/user/appointments/[id]/(member)/components/information/Participants/Participants.tsx
  app/user/appointments/[id]/(member)/information/page.tsx
Labels: 🐞 fix

#236 [fix] 로그인 실패 시 에러메시지 수정
  infrastructure/repositories/SbAuthRepository.ts
Labels: 🐞 fix

#237 [style] 회원가입 페이지 padding 추가
  app/(anon)/signup/signup.module.scss
Labels: 🎨 style

#238 [feat] 약속 만들기 페이지 방 나가기, 삭제 기능 추가
  app/user/appointments/components/AppointmentCard.module.scss
  app/user/appointments/components/AppointmentCard.tsx
  app/user/appointments/components/AppointmentList.module.scss
  app/user/appointments/components/AppointmentList.tsx
  app/user/appointments/hooks/useAppointments.ts
  app/user/appointments/page.tsx
  application/usecases/appointment/DfGetAppointmentCardUsecase.ts
  application/usecases/appointment/dto/AppointmentCardDto.ts
Labels: ✨ feat, 🎨 style

#239 [feat] 멤버삭제시 투표기록 남아있던 오류 수정
  application/usecases/vote/DfSubmitVoteUsecase.ts
  domain/entities/TimeVoteUser.ts
  domain/repositories/MemberRepository.ts
  domain/repositories/PlaceVoteUserRepository.ts
  domain/repositories/TimeVoteUserRepository.ts
  infrastructure/repositories/SbMemberRepository.ts
  infrastructure/repositories/SbPlaceVoteUserRepository.ts
  infrastructure/repositories/SbTimeVoteUserRepository.ts
Labels: 🐞 fix

#240 [style] 약속 생성 완료 페이지 글자 수정
  app/user/appointments/create/components/createComplete.tsx
Labels: 🎨 style

#241 Develop merge to main
  app/(anon)/signup/signup.module.scss
  app/user/appointments/components/AppointmentCard.module.scss
  app/user/appointments/components/AppointmentCard.tsx
  app/user/appointments/components/AppointmentList.module.scss
  app/user/appointments/components/AppointmentList.tsx
  app/user/appointments/create/components/createComplete.tsx
  app/user/appointments/hooks/useAppointments.ts
  app/user/appointments/page.tsx
  application/usecases/appointment/DfGetAppointmentCardUsecase.ts
  application/usecases/appointment/dto/AppointmentCardDto.ts
  application/usecases/vote/DfSubmitVoteUsecase.ts
  domain/entities/TimeVoteUser.ts
  domain/repositories/MemberRepository.ts
  domain/repositories/PlaceVoteUserRepository.ts
  domain/repositories/TimeVoteUserRepository.ts
  infrastructure/repositories/SbAuthRepository.ts
  infrastructure/repositories/SbMemberRepository.ts
  infrastructure/repositories/SbPlaceVoteUserRepository.ts
  infrastructure/repositories/SbTimeVoteUserRepository.ts
Labels: 🌏 배포

#242 [style] 투표결과페이지 버튼위치 수정
  app/user/appointments/[id]/(member)/vote-result/voteResult.module.scss
Labels: 🎨 style

#244 Develop merge to main
  README.md
Labels: 📃 docs

#247 Develop merge to main
  app/user/appointments/create/components/createInformation.tsx
  app/user/appointments/create/hooks/useCreateInformaion.ts
Labels: 🌏 배포

#249 [fix] 약속 만들기 달력 선택 7일까지만 선택되도록 수정
  app/user/appointments/create/hooks/useCreateTime.ts
Labels: 🐞 fix, ✨ feat

#250 Develop merge to main
  app/user/appointments/create/hooks/useCreateTime.ts
Labels: 🌏 배포

#252 [feat] 약속 링크 받고 로그인 후 약속 퀴즈 방으로 이동하기
  app/(anon)/login/hooks/useLogin.ts
  app/api/auth/login/route.ts
  context/UserContext.tsx
Labels: ✨ feat, chore

#253 develop merge to main
  app/(anon)/login/hooks/useLogin.ts
  app/api/auth/login/route.ts
  context/UserContext.tsx
Labels: 🌏 배포

#254 Update README.md
  README.md
Labels: 📃 docs
