Repository FRONT-END-BOOTCAMP-PLUS-3/moongchija, pull requests merged in 2025-01, with the labels that each got.

#6 [style] Components/modal
  components/modal/Modal.module.scss
  components/modal/Modal.tsx
  package-lock.json
  package.json
  pull_request_template.md
Labels: 🎨 style, ⚙ 개발 환경 세팅

#7 Components/input field
  components/input-filed/InputField.module.scss
  components/input-filed/InputFiled.tsx
Labels: 🎨 style

#8 [style] InputField CSS 수정 (radius)
  components/input-filed/InputField.module.scss
Labels: 🎨 style

#12 [style ] input plus button 컴포넌트 생성
  components/input-plus-button/InputPlusButton.module.scss
  components/input-plus-button/InputPlusButton.tsx
Labels: 🎨 style

#14 [file] UI/home-screen 이미지 파일 삭제 및 수정
  public/images/logos/main-logo.svg
  public/images/logos/main-logo.webp
  public/images/logos/sub-logo.svg
  public/images/logos/sub-logo.webp
Labels: ⚙ 개발 환경 세팅, remove

#16 [file] app 폴더 구조 변경 및 globals.css 수정
  app/(with-arrow-header)/create-appointment/ confirm/[id]/page.tsx
  app/(with-arrow-header)/create-appointment/page.tsx
  app/(with-arrow-header)/entry/[id]/page.tsx
  app/(with-arrow-header)/layout.tsx
  app/(with-arrow-header)/vote-result/[id]/page.tsx
  app/(with-arrow-header)/vote/[id]/page.tsx
  app/(with-icon-header)/detail/[id]/gallery/page.tsx
  app/(with-icon-header)/detail/[id]/information/page.tsx
  app/(with-icon-header)/detail/[id]/page.tsx
  app/(with-icon-header)/detail/[id]/settlement/page.tsx
  app/(with-icon-header)/layout.tsx
  app/(with-icon-header)/list/page.tsx
  app/(with-icon-header)/mypage/page.tsx
  app/globals.css
Labels: 📃 docs, ⚙ 개발 환경 세팅

#17 Components/button
  app/globals.css
  app/layout.tsx
  components/Button.tsx
  components/button/Button.module.scss
  components/button/Button.tsx
  components/input-plus-button/InputPlusButton.module.scss
  components/input-plus-button/InputPlusButton.tsx
Labels: 🎨 style

#19 [style] button 스타일 수정
  components/Button.tsx
  components/button/Button.module.scss
  components/button/Button.tsx
Labels: 🎨 style

#20 [style] UI작업 초기화면 페이지 작업
  app/page.module.css
  app/page.module.scss
  app/page.tsx
Labels: 🎨 style, remove

#21 [fix] header 이미지 경로 및 link 수정
  components/header/DropdownMenu.tsx
  components/header/IconHeader.tsx
Labels: 🐞 fix

#22 [style] input field 수정
  app/globals.css
  components/input-filed/InputField.module.scss
  components/input-filed/InputFiled.tsx
Labels: 🎨 style

#23 [style] globals.css 수정
  app/globals.css
Labels: 🎨 style

#24 [style] (01.23 최신) InputField 오류 메세지 기능 추가 및 스타일 수정
  components/input-filed/InputField.module.scss
  components/input-filed/InputFiled.tsx
Labels: ✨ feat, 🎨 style

#25 UI/login
  app/login/_components/LoginForm.module.scss
  app/login/_components/LoginForm.tsx
  app/login/_components/LogoWithTitle.module.scss
  app/login/_components/LogoWithTitle.tsx
  app/login/login.module.scss
  app/login/page.tsx
  public/images/logos/kakao-logo.svg
Labels: 🎨 style

#26 UI/login
  app/login/_components/LogoWithTitle.module.scss
  app/login/login.module.scss
  app/login/page.tsx
Labels: 🎨 style

#27 [style] Button 공통 컴포넌트 height -> padding 으로 수정
  components/button/Button.module.scss
Labels: 🎨 style

#28 [style] vote페이지에 시간투표하는 컴포넌트 제작 (TimeVote.tsx)
  app/(with-arrow-header)/vote/[id]/_components/TimeVote.module.scss
  app/(with-arrow-header)/vote/[id]/_components/TimeVote.tsx
  app/(with-arrow-header)/vote/[id]/page.tsx
  app/(with-arrow-header)/vote/[id]/vote.module.scss
  app/globals.css
Labels: ✨ feat, 🎨 style

#29 [style] signup 페이지 UI 작업
  app/login/_components/LogoWithTitle.module.scss
  app/login/_components/LogoWithTitle.tsx
  app/signup/_components/AuthForm.module.scss
  app/signup/_components/AuthForm.tsx
  app/signup/_hooks/useInput.ts
  app/signup/page.tsx
  app/signup/signup.module.scss
Labels: 🎨 style

#30 [style] circle button 컴포넌트 생성
  components/circleButton/CircleButton.module.scss
  components/circleButton/CircleButton.tsx
Labels: 🎨 style

#32 [style] 회원가입 페이지 유효성 검사 규칙 및 UI 작업
  app/signup/_components/AuthForm.tsx
  app/signup/_hooks/useInput.ts
  app/signup/_hooks/useValidate.ts
  components/input-filed/InputField.module.scss
  components/input-filed/InputFiled.tsx
Labels: 🎨 style, chore

#33 [style] TabMenu 컴포넌트 생성
  components/tabMenu/TabMenu.module.scss
  components/tabMenu/TabMenu.tsx
Labels: 🎨 style

#36 [style] 약속 상세 페이지 구현 및 스타일링
  app/(with-icon-header)/detail/[id]/information/information.module.scss
  app/(with-icon-header)/detail/[id]/information/page.tsx
  app/(with-icon-header)/detail/[id]/page.tsx
  app/(with-icon-header)/detail/_components/DetailTabMenu/DetailTabMenu.module.scss
  app/(with-icon-header)/detail/_components/DetailTabMenu/DetailTabMenu.tsx
  app/(with-icon-header)/detail/_components/InformationDetail/InformationDetail.module.scss
  app/(with-icon-header)/detail/_components/InformationDetail/InformationDetail.tsx
  app/(with-icon-header)/detail/_components/NoticeBox/NoticeBox.module.scss
  app/(with-icon-header)/detail/_components/NoticeBox/NoticeBox.tsx
  app/(with-icon-header)/detail/_components/NoticeDetail/NoticeDetail.module.scss
  app/(with-icon-header)/detail/_components/NoticeDetail/NoticeDetail.tsx
  app/(with-icon-header)/detail/_components/Participants/Participants.module.scss
  app/(with-icon-header)/detail/_components/Participants/Participants.tsx
  app/globals.css
  components/button/Button.tsx
Labels: 🎨 style

#35 [style] UI/my page 작업
  app/(with-icon-header)/mypage/_components/AppointmentCount.module.scss
  app/(with-icon-header)/mypage/_components/AppointmentCount.tsx
  app/(with-icon-header)/mypage/_components/Calendar.module.scss
  app/(with-icon-header)/mypage/_components/Calendar.tsx
  app/(with-icon-header)/mypage/mypage.module.scss
  app/(with-icon-header)/mypage/page.tsx
  app/signup/_components/AuthForm.tsx
Labels: 🎨 style

#37 [style] vote-result-timeVote 스타일 추가
  app/(with-arrow-header)/vote-result/[id]/_components/TimeResult.module.scss
  app/(with-arrow-header)/vote-result/[id]/_components/TimeResult.tsx
  app/(with-arrow-header)/vote-result/[id]/page.tsx
  app/(with-arrow-header)/vote-result/[id]/voteResult.module.scss
Labels: 🎨 style

#39 [file] 파일 구조 변경 : 기존 UI 기준 -> user 기준 폴더 구성으로 변경
  app/(anon)/login/components/LoginForm.module.scss
  app/(anon)/login/components/LoginForm.tsx
  app/(anon)/login/components/LogoWithTitle.module.scss
  app/(anon)/login/components/LogoWithTitle.tsx
  app/(anon)/login/login.module.scss
  app/(anon)/login/page.tsx
  app/(anon)/page.module.scss
  app/(anon)/page.tsx
  app/(anon)/signup/components/AuthForm.module.scss
  app/(anon)/signup/components/AuthForm.tsx
  app/(anon)/signup/hooks/useInput.ts
  app/(anon)/signup/hooks/useValidate.ts
  app/(anon)/signup/page.tsx
  app/(anon)/signup/signup.module.scss
  app/(with-arrow-header)/create-appointment/page.tsx
  app/(with-arrow-header)/layout.tsx
  app/(with-icon-header)/layout.tsx
  app/user/appointments/[id]/ confirm/page.tsx
  app/user/appointments/[id]/components/detail/DetailTabMenu/DetailTabMenu.module.scss
  app/user/appointments/[id]/components/detail/DetailTabMenu/DetailTabMenu.tsx
  app/user/appointments/[id]/components/detail/InformationDetail/InformationDetail.module.scss
  app/user/appointments/[id]/components/detail/InformationDetail/InformationDetail.tsx
  app/user/appointments/[id]/components/detail/NoticeBox/NoticeBox.module.scss
  app/user/appointments/[id]/components/detail/NoticeBox/NoticeBox.tsx
  app/user/appointments/[id]/components/detail/NoticeDetail/NoticeDetail.module.scss
  app/user/appointments/[id]/components/detail/NoticeDetail/NoticeDetail.tsx
  app/user/appointments/[id]/components/detail/Participants/Participants.module.scss
  app/user/appointments/[id]/components/detail/Participants/Participants.tsx
  app/user/appointments/[id]/entry/page.tsx
  app/user/appointments/[id]/gallery/page.tsx
  app/user/appointments/[id]/information/information.module.scss
  app/user/appointments/[id]/information/page.tsx
  app/user/appointments/[id]/settlement/page.tsx
  app/user/appointments/[id]/vote-result/components/TimeResult.module.scss
  app/user/appointments/[id]/vote-result/components/TimeResult.tsx
  app/user/appointments/[id]/vote-result/page.tsx
  app/user/appointments/[id]/vote-result/voteResult.module.scss
  app/user/appointments/[id]/vote/components/PlaceVote.module.scss
  app/user/appointments/[id]/vote/components/PlaceVote.tsx
  app/user/appointments/[id]/vote/components/TimeVote.module.scss
  app/user/appointments/[id]/vote/components/TimeVote.tsx
  app/user/appointments/[id]/vote/page.tsx
  app/user/appointments/[id]/vote/vote.module.scss
  app/user/appointments/components/AppointmentList.module.scss
  app/user/appointments/components/AppointmentList.tsx
  app/user/appointments/components/VotingList.module.scss
  app/user/appointments/components/VotingList.tsx
  app/user/appointments/components/listBox.module.scss
  app/user/appointments/components/listBox.tsx
  app/user/appointments/create/page.tsx
  app/user/appointments/list.module.scss
  app/user/appointments/page.tsx
  app/user/mypage/components/AppointmentCount.module.scss
  app/user/mypage/components/AppointmentCount.tsx
  app/user/mypage/components/Calendar.module.scss
  app/user/mypage/components/Calendar.tsx
  app/user/mypage/mypage.module.scss
  app/user/mypage/page.tsx
Labels: ⚙ 개발 환경 세팅, remove

#40 [file] mypage -> user/page 로 변경 votes 폴더 구조 변경
  app/user/components/AppointmentCount.module.scss
  app/user/components/AppointmentCount.tsx
  app/user/components/Calendar.module.scss
  app/user/components/Calendar.tsx
  app/user/mypage.module.scss
  app/user/page.tsx
  app/user/votes/[id]/components/PlaceVote.module.scss
  app/user/votes/[id]/components/PlaceVote.tsx
  app/user/votes/[id]/components/TimeVote.module.scss
  app/user/votes/[id]/components/TimeVote.tsx
  app/user/votes/[id]/page.tsx
  app/user/votes/[id]/result/components/TimeResult.module.scss
  app/user/votes/[id]/result/components/TimeResult.tsx
  app/user/votes/[id]/result/page.tsx
  app/user/votes/[id]/result/voteResult.module.scss
  app/user/votes/[id]/vote.module.scss
Labels: ⚙ 개발 환경 세팅, remove

#41 [file] user/vote,vote-result -> user/appointment/[id]/vote,vote-resul…
  app/user/appointments/[id]/vote/components/PlaceVote.module.scss
  app/user/appointments/[id]/vote/components/PlaceVote.tsx
  app/user/appointments/[id]/vote/components/TimeVote.module.scss
  app/user/appointments/[id]/vote/components/TimeVote.tsx
  app/user/appointments/[id]/vote/page.tsx
  app/user/appointments/[id]/vote/vote.module.scss
  app/user/appointments/[id]/voteResult/components/TimeResult.module.scss
  app/user/appointments/[id]/voteResult/components/TimeResult.tsx
  app/user/appointments/[id]/voteResult/page.tsx
  app/user/appointments/[id]/voteResult/voteResult.module.scss
Labels: ⚙ 개발 환경 세팅

#42 [refactor] 컴포넌트 로직 분리 및 스타일 변경
  app/(anon)/signup/components/AuthForm.module.scss
  app/(anon)/signup/components/AuthForm.tsx
  app/(anon)/signup/components/EmailInputField.module.scss
  app/(anon)/signup/components/EmailInputField.tsx
  app/(anon)/signup/constants/emailDomains.ts
  app/(anon)/signup/hooks/useForm.ts
  app/(anon)/signup/hooks/useInput.ts
  app/(anon)/signup/hooks/useValidate.ts
Labels: 🎨 style, 🔧 refactor, chore

#43 [fix] 비밀번호 유효성 검사 순서
  app/(anon)/signup/hooks/useForm.ts
  app/(anon)/signup/hooks/useInput.ts
Labels: 🐞 fix, 🔧 refactor

#44 [style] vote-result 페이지 시간투표결과 컴포넌트 ui작성
  app/user/appointments/[id]/vote-result/components/TimeResult.module.scss
  app/user/appointments/[id]/vote-result/components/TimeResult.tsx
  app/user/appointments/[id]/vote-result/layout.tsx
  app/user/appointments/[id]/vote-result/page.tsx
  app/user/appointments/[id]/vote-result/voteResult.module.scss
Labels: 🎨 style

#45 [feat] vote페이지-> 시간/장소투표페이지로 분리
  app/user/appointments/[id]/vote-place/layout.tsx
  app/user/appointments/[id]/vote-place/page.tsx
  app/user/appointments/[id]/vote-place/votePlace.module.scss
  app/user/appointments/[id]/vote-time/layout.tsx
  app/user/appointments/[id]/vote-time/page.tsx
  app/user/appointments/[id]/vote-time/voteTime.module.scss
  app/user/appointments/[id]/vote/page.tsx
  app/user/appointments/[id]/vote/vote.module.scss
  app/user/appointments/[id]/voteResult/page.tsx
Labels: ✨ feat, 🔧 refactor

#47 [style] 마이페이지 UI 수정 및 달력 제외 완성
  app/user/mypage.module.scss
  app/user/page.tsx
Labels: 🎨 style

#48 [reafactor] 마이페이지 컴포넌트 구조 리팩토링
  app/user/components/DeleteAccountModalContent.module.scss
  app/user/components/DeleteAccountModalContent.tsx
  app/user/components/UserAppointmentCount.module.scss
  app/user/components/UserAppointmentCount.tsx
  app/user/components/UserImage.module.scss
  app/user/components/UserImage.tsx
  app/user/components/UserInfo.module.scss
  app/user/components/UserInfo.tsx
  app/user/components/UserName.module.scss
  app/user/components/UserName.tsx
  app/user/components/UserProfile.module.scss
  app/user/components/UserProfile.tsx
  app/user/page.tsx
Labels: 🔧 refactor

#49 Feat/my page/calendar
  app/user/components/Calendar.module.scss
  app/user/components/Calendar.tsx
  app/user/components/MyCalendar.scss
  app/user/components/MyCalendar.tsx
  app/user/page.tsx
  package-lock.json
  package.json
Labels: ✨ feat, 🎨 style, 🔧 refactor, rename, remove

#50 [feat] 마이페이지 Emoji 수정 모달 추가
  app/user/components/UserImage.tsx
  app/user/components/UserImageModalContent.module.scss
  app/user/components/UserImageModalContent.tsx
Labels: ✨ feat, 🎨 style

#51 [refactor] 회원가입 페이지 하단 로그인 하러가기 링크 추가
  app/(anon)/login/login.module.scss
  app/(anon)/login/page.tsx
  app/(anon)/signup/components/AuthForm.module.scss
  app/(anon)/signup/components/AuthForm.tsx
Labels: 🎨 style, 🔧 refactor

#52 [style] UI/appointments
  app/user/appointments/AppointmentsPage.module.scss
  app/user/appointments/components/AppointmentCard.module.scss
  app/user/appointments/components/AppointmentCard.tsx
  app/user/appointments/components/AppointmentList.module.scss
  app/user/appointments/components/AppointmentList.tsx
  app/user/appointments/components/VotingList.module.scss
  app/user/appointments/components/VotingList.tsx
  app/user/appointments/components/listBox.tsx
  app/user/appointments/list.module.scss
  app/user/appointments/page.tsx
Labels: ✨ feat, 🎨 style

#53 [style] input-field 너비 100%로 변경
  components/input-filed/InputField.module.scss
Labels: 🎨 style

#54 [feat] 회원가입 기능 추가
  app/(anon)/signup/components/AuthForm.tsx
  app/(anon)/signup/hooks/useForm.ts
  app/api/auth/signup/route.ts
  application/usecases/auth/SignUpUseCase.ts
  domain/entities/User.ts
  domain/repositories/UserEmojiRepository.ts
  domain/repositories/UserRepository.ts
  infrastructure/repositories/SbUserEmojiRepository.ts
  infrastructure/repositories/SbUserRepository.ts
Labels: 🐞 fix, ✨ feat, 🔧 refactor

#55 [feat] 이메일 중복 오류 메시지 표시 추가
  app/(anon)/signup/components/AuthForm.tsx
Labels: ✨ feat

#57 [feat] 회원가입 페이지 닉네임 중복 검사 기능 구현
  app/(anon)/signup/components/AuthForm.tsx
  app/(anon)/signup/components/EmailInputField.tsx
  app/(anon)/signup/constants/EMAIL_DOMAINS.ts
  app/(anon)/signup/hooks/useForm.ts
  app/api/auth/check-nickname/route.ts
  application/usecases/auth/UserNicknameCheckUsecase.ts
  components/button/Button.tsx
  components/input-filed/InputField.module.scss
  components/input-filed/InputFiled.tsx
  domain/repositories/UserRepository.ts
  infrastructure/repositories/SbUserRepository.ts
Labels: ✨ feat, 🔧 refactor, rename

#58 [fix] 닉네임 변경 시 중복검사 상태 초기화 및 버튼 활성화 로직 수정
  app/(anon)/signup/components/AuthForm.tsx
Labels: 🐞 fix

#60 [feat] 로그인 및 로그아웃 기능 추가
  app/(anon)/login/components/LoginForm.tsx
  app/api/auth/login/route.ts
  app/api/auth/logout/route.ts
  app/api/auth/signup/route.ts
  app/user/page.tsx
  application/usecases/auth/LoginUsecase.ts
  application/usecases/auth/LogoutUsecase.ts
  application/usecases/auth/SignUpUseCase.ts
  domain/entities/Auth.ts
  domain/repositories/AuthRepository.ts
  infrastructure/repositories/SbAuthRepository.ts
Labels: ✨ feat

#61 [style] UI/create
  app/user/appointments/Appointments.module.scss
  app/user/appointments/[id]/gallery/page.tsx
  app/user/appointments/create/components/CircleIndicator.module.scss
  app/user/appointments/create/components/CircleIndicator.tsx
  app/user/appointments/create/create.module.scss
  app/user/appointments/create/page.tsx
  app/user/appointments/page.tsx
Labels: ✨ feat, 🎨 style

#62 [style] UI/create/time
  app/user/appointments/create/components/CircleIndicator.tsx
  app/user/appointments/create/information/information.module.scss
  app/user/appointments/create/information/page.tsx
  app/user/appointments/create/time/page.tsx
  app/user/appointments/create/time/time.module.scss
  app/user/appointments/page.tsx
  package-lock.json
  package.json
Labels: ✨ feat, 🎨 style, ⚙ 개발 환경 세팅

#63 [fix] Appointments.module.scss 오타 수정 a -> A
  app/user/appointments/page.tsx
Labels: 🐞 fix

#64 [UI/information] 상세 페이지 스타일 수정 및 더미데이터 적용
  app/user/appointments/[id]/components/const/banks.ts
  app/user/appointments/[id]/components/detail/Test/dummyData.ts
  app/user/appointments/[id]/components/detail/dummyData/detailDummyData.ts
  app/user/appointments/[id]/components/detail/types/detailTypes.ts
  app/user/appointments/[id]/components/gallery/galleryDetail/galleryDetail.tsx
  app/user/appointments/[id]/components/information/InformationDetail/InformationDetail.tsx
  app/user/appointments/[id]/components/information/NoticeBox/NoticeBox.module.scss
  app/user/appointments/[id]/components/information/NoticeBox/NoticeBox.tsx
  app/user/appointments/[id]/components/information/NoticeDetail/NoticeDetail.tsx
  app/user/appointments/[id]/components/information/Participants/Participants.tsx
  app/user/appointments/[id]/components/settlement/SettlementDetail/SettlementDetail.module.scss
  app/user/appointments/[id]/components/settlement/SettlementDetail/SettlementDetail.tsx
  app/user/appointments/[id]/components/settlement/SettlementModalContent/SettlementModalContent.tsx
  app/user/appointments/[id]/gallery/page.tsx
  app/user/appointments/[id]/information/page.tsx
  app/user/appointments/[id]/settlement/page.tsx
Labels: ✨ feat, 🎨 style

#65 [style] 약속확정페이지 디자인추가
  app/user/appointments/[id]/ confirm/page.tsx
  app/user/appointments/[id]/confirm/confirm.module.scss
  app/user/appointments/[id]/confirm/layout.tsx
  app/user/appointments/[id]/confirm/page.tsx
  app/user/appointments/[id]/vote-result/page.tsx
Labels: 🎨 style

#66 [style] 약속확정완료 페이지 스타일 추가
  app/user/appointments/[id]/confirm/complete/complete.module.scss
  app/user/appointments/[id]/confirm/complete/page.tsx
  app/user/appointments/[id]/confirm/page.tsx
Labels: 🎨 style

#67 [feat] url에서 appointment id 값 가져오는 방식 변경
  app/user/appointments/[id]/vote-place/page.tsx
  app/user/appointments/[id]/vote-result/page.tsx
  app/user/appointments/[id]/vote-time/page.tsx
Labels: ✨ feat

#68 [refactor] 카카오 로그인 컴포넌트 분리
  app/(anon)/login/components/KakaoLogin.module.scss
  app/(anon)/login/components/KakaoLogin.tsx
  app/(anon)/login/login.module.scss
  app/(anon)/login/page.tsx
Labels: 🔧 refactor

#69 [style] UI/create/place
  app/user/appointments/create/place/page.tsx
  app/user/appointments/create/place/place.module.scss
  app/user/appointments/page.tsx
Labels: ✨ feat, 🎨 style

#70 [style] create complete 페이지 완료
  app/user/appointments/create/complete/complete.module.scss
  app/user/appointments/create/complete/page.tsx
  app/user/appointments/create/place/page.tsx
Labels: ✨ feat, 🎨 style

#71 [style] 방 참여 페이지 완료
  app/user/appointments/[id]/entry/entry.module.scss
  app/user/appointments/[id]/entry/page.tsx
  app/user/appointments/create/complete/page.tsx
Labels: ✨ feat, 🎨 style

#72 [fix] 회원가입 완료 후 자동으로 로그인
  app/(anon)/signup/components/AuthForm.tsx
  app/api/auth/signup/route.ts
  app/globals.css
  application/usecases/auth/SignUpUseCase.ts
  infrastructure/repositories/SbUserRepository.ts
Labels: 🐞 fix, ✨ feat

#73 [feat] 카카오 로그인 기능 구현
  app/(anon)/login/components/KakaoLogin.tsx
  app/api/auth/callback/route.ts
  app/api/auth/kakao-login-url/route.ts
  application/usecases/auth/KakaoLoginUsecase.ts
  application/usecases/auth/SignUpUseCase.ts
  domain/repositories/UserRepository.ts
  infrastructure/repositories/SbUserRepository.ts
Labels: ✨ feat

#74 UI/vote/feedback
  app/globals.css
  app/user/appointments/[id]/confirm/complete/complete.module.scss
  app/user/appointments/[id]/confirm/complete/page.tsx
  app/user/appointments/[id]/confirm/confirm.module.scss
  app/user/appointments/[id]/confirm/layout.tsx
  app/user/appointments/[id]/confirm/page.tsx
  app/user/appointments/[id]/vote-place/layout.tsx
  app/user/appointments/[id]/vote-place/page.tsx
  app/user/appointments/[id]/vote-place/votePlace.module.scss
  app/user/appointments/[id]/vote-result/components/PlaceResult.module.scss
  app/user/appointments/[id]/vote-result/components/PlaceResult.tsx
  app/user/appointments/[id]/vote-result/components/TimeResult.module.scss
  app/user/appointments/[id]/vote-result/layout.tsx
  app/user/appointments/[id]/vote-result/page.tsx
  app/user/appointments/[id]/vote-result/voteResult.module.scss
  app/user/appointments/[id]/vote-time/layout.tsx
  app/user/appointments/[id]/vote-time/page.tsx
  app/user/appointments/[id]/vote-time/voteTime.module.scss
  components/button/Button.module.scss
Labels: 🎨 style

#75 [style] 투표 결과 페이지 버튼 fix 삭제, 시간/장소 컴포넌트 높이 맞춤
  app/user/appointments/[id]/vote-result/components/PlaceResult.module.scss
  app/user/appointments/[id]/vote-result/components/TimeResult.module.scss
  app/user/appointments/[id]/vote-result/voteResult.module.scss
Labels: 🎨 style

#76 [style] 탭 메뉴 컴포넌트 높이 패딩 값으로 변경
  components/tabMenu/TabMenu.module.scss
Labels: 🎨 style

#77 [style] UI/appointments
  app/user/appointments/Appointments.module.scss
  app/user/appointments/components/AppointmentCard.module.scss
  app/user/appointments/components/AppointmentCard.tsx
  app/user/appointments/page.tsx
  components/tabMenu/TabMenu.module.scss
  utils/dateUtils/dateUtils.ts
Labels: 🎨 style, 🔧 refactor
